import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/footer";
import MyContextProvider from "@/store/context/MyContextProvider";
import Authprovider from "@/components/Authprovider/Authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DaSouk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Authprovider>
        <MyContextProvider>
          <Navbar />
          <main style={{ marginTop: "9vh" }}>{children}</main>
          <Footer />
        </MyContextProvider>
        </Authprovider>
      </body>
    </html>
  );
}
